### PR TITLE
Fix zap insert constraint (EventZapDao.insert) crash

### LINKED ISSUE #141: Two fast zap clicks on a specific note make Primal crash
Two fast zap clicks on a specific note make Primal crash.
Note: note1dqecfx3dlqdw84se9lpfqfmqnzfr9csfgnjxanz5d4gxtwaz3h6quslpr9

https://github.com/PrimalHQ/primal-android-app/assets/1178856/953ca254-11bf-4861-a527-4fd731866a1f

### PR DESCRIPTION
**Pull request by mehmedalijaK**
Closes #141

### CODE REVIEW

**Review by AleksandarIlic — CHANGES_REQUESTED** [review]
This would merge zaps with same `zapCreatedAt`. Let's better create an internal auto increment primary key instead of trying to do composite primary key from existing fields..

File: data/local-caching/src/commonMain/kotlin/net/primal/data/local/dao/events/EventZap.kt [hunk 1]
```diff
@@ -1,17 +1,18 @@
...
 import net.primal.domain.links.CdnImage
 import net.primal.domain.premium.PrimalLegendProfile
 
 @Entity(
-    primaryKeys = [
-        "zapSenderId",
-        "eventId",
-        "zapRequestAt",
+    indices = [
+        Index(value = ["zapSenderId", "eventId", "zapRequestAt"]),
```
Comment (AleksandarIlic) [inline data/local-caching/src/commonMain/kotlin/net/primal/data/local/dao/events/EventZap.kt:11]: I'm not sure if we should have this fields indexed? Any particular reason? If it's just because this was a Primary Key in the past, I think we can drop it.
